Allow to remove switches when converting
ie3-institute/simBench2psdm pull request #68
Opened 2021-08-03 13:57 UTC by ckittl

Closes #66

2021-08-19 07:57 UTC, t-ober requested changes
I think I actually got it! 😂
Just a few very minor things where most of them are optional.

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    val targetConversion = targetNodes.par
`joinTargetNodeKeys` und `joinTargetConversion` ?

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    * marked explicitly as junctions. During this travel, every node we come along gets an [[SubnetOverride]] instance
```suggestion
    * marked explicitly as junctions. During this travel, every node we come along gets a [[SubnetOverride]] instance
```

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    * marked explicitly as junctions. During this travel, every node we come along gets an [[SubnetOverride]] instance
:nerd_face:

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    * explicit subnet numbers are provided.
More generally for understanding the algorithm it might be helpful if there was a short documentation on each systems conception of a subnet so we know what conceptually needs to be done in order for the conversion which would make the algorithm clearer.

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    *
Just out of curiosity: Why would there be a node that isn't connected to any branch? Is that just for fault tolerance of simbench grid fuck ups?

2021-08-19 07:57 UTC, t-ober commented on src/main/scala/edu/ie3/simbench/convert/SubnetConverter.scala
> +  * [[GridConverter]]
```suggestion
  * [[GridConverter.determineSubnetOverrides()]]
```

2021-08-19 07:57 UTC, t-ober commented on src/test/scala/edu/ie3/simbench/convert/GridConverterSpec.scala
> +            group.contains(switchHI)
```suggestion
            group.contains(switchHI) shouldBe true
```

2021-08-19 07:57 UTC, t-ober commented on docs/diagrams/RemoveSwitches.puml
> +note right: By iterating over all existing switches\nand building bags of connected nodes.\nIf a node of a following switch is already\nin a bag, then add the switch to this\nswitch group.
```suggestion
note right: By iterating over all existing switches\nand building bags of nodes that are directly connected via switches.\nIf a node of a following switch is already\nin a bag, then add the switch to this\nswitch group.
```

2021-08-19 11:43 UTC, ckittl commented on src/main/scala/edu/ie3/simbench/convert/LoadConverter.scala
> +      .toMap
Yes, that could be overcome, but that would mean a lot of generification there. For now, I left it this way. It may come to larger refactoring anyway, because not many things are done in parallel. Therefore, the converter is not too fast...

2021-08-19 11:53 UTC, ckittl commented on src/main/scala/edu/ie3/simbench/convert/GridConverter.scala
> +    *
No it's not just to be sure. Sometimes there are grid structures with a "major station" (in German called Schaltwerk or Schwerpunktstation). They are somewhat built like a primary substation, but without connection to a higher voltage level. Typically, they are connected to a primary substation via one or two feeders with a high rated transport capacity.

However, if that major station is operated in open loop, especially, all switches are open, it might happen that we totally disconnect the associated nodes. Thereby the station would be isolated and in most simulations lead to an error.

2021-08-25 06:19 UTC, t-ober approved these changes

2021-08-25 06:19 UTC, merged